### ISSUE TITLE
批量执行只会出现终端，不会执行

### ISSUE THREAD

**Issue by juju486** [424490034/webpcilvds#2]
如题。
加了几个本地项目，批量执行build 失败。
后面试了其他的也是不行的。只有终端窗口

**Comment by 424490034** [comment]
这个设计时候考虑场景比较少，可以通过对应项目自定义指令，然后通过谷歌插件或者软件手动分开调用， 这个软件目前正在进行electron版本升级和架构重构，感兴趣也可以自己对这个项目修改
